### ISSUE TITLE
Capture set after popup menu item selected causes next mouse click to be ignored

### ISSUE THREAD

**Issue by sagantech** [steinbergmedia/vstgui#93] opened 2019-01-28 20:21 UTC
Currently in win32frame.cpp mouse capture is set after all mouse clicks. If the click caused a popup menu to occur and process, then there is no reason to setcapture. One possible solution is below. Do not set capture if the mouse button is up. win32frame.cpp line 866:

        {//only set capture on mousedown if not left button or left button is still down. It is not after calling trackpopup menu
             if ((buttons & kLButton) == 0 || GetAsyncKeyState (VK_LBUTTON) < 0)
                 SetCapture (getPlatformWindow ());
        }

**Comment by esaruoho** [comment] 2019-02-06 16:54
@sagantech line 866 of win32frame.cpp bears no resemblance to that line you sent. the only bit of code i can see that even mentions `vk_lbutton` is on 322. 

could you create a fork of `vstgui` and add in your fix and create a PR instead?

**Comment by sagantech** [comment] 2019-02-06 17:59
Did you search for 'SetCapture"? I see this starting on line 805  of this repository (today) :

			CPoint where (GET_X_LPARAM (lParam), GET_Y_LPARAM (lParam));
			if (pFrame->platformOnMouseDown (where, buttons) == kMouseEventHandled && getPlatformWindow ())
				SetCapture (getPlatformWindow ());
			return 0;
Replace the setcapture with the code above.

**Comment by sagantech** [comment] 2019-02-06 18:04
> could you create a fork of `vstgui` and add in your fix and create a PR instead?

I could but I do not submit code without testing and I am not testing with the debugger being so slow on Windows 7.

**Comment by esaruoho** [comment] 2019-02-06 18:19
do you mean like this:
```
		CPoint where (GET_X_LPARAM (lParam), GET_Y_LPARAM (lParam));
		if (pFrame->platformOnMouseDown (where, buttons) == kMouseEventHandled && getPlatformWindow ())
    {//only set capture on mousedown if not left button or left button is still down. It is not after calling trackpopup menu
         if ((buttons & kLButton) == 0 || GetAsyncKeyState (VK_LBUTTON) < 0)
             SetCapture (getPlatformWindow ());
    }
 		return 0;
```

**Comment by sagantech** [comment] 2019-02-06 18:33
yes

**Comment by sagantech** [comment] 2019-02-06 18:34
You should test it before submitting a pull request.

**Comment by esaruoho** [comment] 2019-02-06 18:49
> You should test it before submitting a pull request.

i have no way of testing vstgui stuff.

**Comment by esaruoho** [comment] 2019-02-06 18:51
@sagantech here's the PR.
https://github.com/steinbergmedia/vstgui/pull/95

**Comment by sagantech** [comment] 2019-02-06 18:57
If you can build surge you can test vstgui!

**Comment by baconpaul** [comment] 2019-02-11 01:41
Folks: Per @scheffle this was a bug in surge code not a bug in vstgui. I've patched surge and we are now OK. I can't close this issue though.

**Closed** 2019-02-11 09:57 UTC
